version: "3.7"
services:
  mqtt5:
    container_name: mqtt5
    build: 
      context: .
      dockerfile: dockerfiles/broker.Dockerfile
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  influxdb:
    container_name: influxdb
    build: 
      context: .
      dockerfile: dockerfiles/influxdb.Dockerfile
    env_file:
      - config/.env
    ports:
    - "8086:8086"

networks:
  default:
    name: mqtt5-network
