version: "3.7"
services:
  mqtt5:
    container_name: mqtt5
    build: 
      context: .
      dockerfile: dockerfiles/broker.Dockerfile
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

volumes:
  config:
  data:
  log:

networks:
  default:
    name: mqtt5-network
