version: "3.7"
services:
  mqtt5:
    container_name: mqtt5
    build: 
      context: .
      dockerfile: dockerfiles/broker.Dockerfile
    network_mode: host
    restart: unless-stopped
  influxdb:
    container_name: influxdb
    build: 
      context: .
      dockerfile: dockerfiles/influxdb.Dockerfile
    network_mode: host
    env_file:
      - config/.env